#let genai-declaration = (
    usage: true,
    data-usage: (
      sensitive: "with-authorization",
      copyright: "without-authorization",
      personal: "not-used",
      followed-terms: true,
      explanation: [_[Add an example] e.g. "the materials were protected but
        permitted use for this purpose" or "the terms of use, which can be found
        at this address (...), prevent the use I have made, but it was essential
        given the nature of the work_],
    ),
    technical-usage: (
      // If you think it is necessary to include it, add it in each case:
      // *using the prompt* ...
      //            (write the request made to the IAG)
      // *having as interaction* ...
      //            (describe what interaction you made with the IAG after the
      //            prompt's response)
      //
      // Comment out the ones that don't apply.
      //
      // Example: I declare that I have made use of the Generative AI system
      // Chat GPT 3.5 to search for information using the prompt: "Tell me a
      // concrete example that illustrates the application of the urban planning
      // proposal of the 15-minute City in Spain", having as interaction the
      // proposition of the concrete example of the Chamartín district that has
      // been reflected in the report.
      documentation: [_[Add an example] For example: I have asked for a list of
        alternatives to address the problem stated at the beginning of the
        paper._],
      review: [_[Add an example] For example: I have asked for paragraphs to be
        rewritten to shorten the conclusions while keeping the same ideas
        already written._],
      research: [_[Add an example] For example: The questions asked were aimed
        at [finding definitions, explanations of processes, examples of use,
        lists of risks of use...]._],
      references: [_Bibliography search._],
      summary: [_Summary of bibliography consulted._],
      translation: [_Translation of texts consulted._],
      assistance-coding: [_[Add an example of the usual flow of use for
        programming] For example: I have asked for explanations about a code in
        Python._],
      generating-content: [_[indicate its use in this section, as well as in a
        footnote to the figure/element generated by Generative AI] For example:
        Source: own elaboration with the help of Midjourney._],
      optimization: [_[Add an example of the usual flow of use to optimise] For
        example: I have asked for help to correct and explain errors in a code
        that was not working properly._],
      data-processing: [_[Add an example] For example: after collecting the
        data, I have asked for guidance in normalising the data in preparation
        for the subsequent analysis._],
      idea-inspiration: [_[Add an example] For example: once I was clear about
        the objective of the work, I asked for ideas to cover the project from a
        multidisciplinary approach._],
      other: [_Other uses linked to the generation of specific points of the
        specific development of the work._],
    ),
    usage-reflection: [_Please provide a personal assessment (free format) of
      the strengths and weaknesses you have identified in the use of Generative
      AI tools in the development of your work. Mention if it has helped you in
      the learning process, or in the development or drawing conclusions from
      your work._],
  )